server:
  port: 8006

spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import: nacos:request_deliver.yml?group=common
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        # 指定命名空间
        namespace: ${spring.profiles.active}
        import-check:
          enabled: false
  datasource:
    driver-class-name: ${osir.datasource.driver-class-name}
    url: ${osir.datasource.url}
    username: ${osir.datasource.username}
    password: ${osir.datasource.password}
  # 配置redis数据源
  data:
    redis:
      host: ${osir.redis.host}
      database: ${osir.redis.database}
      password: ${osir.redis.password}
      port: ${osir.redis.port}

# mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.osir.takeoutpojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

